spring:
  application:
    name: admin-server
server:
  port: 9300

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/