server:
  port: 9200
service-url:
  user-service: http://localhost:8200
spring:
  cloud:
    gateway:
      routes:
        - id: path_route #路由的ID
          uri: ${service-url.user-service}/user/{id} #匹配后路由地址
#          After Route Predicate
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user/{id}