server:
  port: 8010
spring:
  application:
    name: eureka-client #指定服务名称
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
#      无需验证的注册中心
#      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/ #配置注册中心地址
        defaultZone: http://dr5hx:123456@localhost:8003/eureka/
