server:
  port: 8901
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Dr5hx/springcloud.git
          username:
          password:
          clone-on-start: true #开启启动时直接从git获取配置
  security: #配置用户名和密码
    user:
      name: dr5hx
      password: 123456